### ISSUE TITLE
Error in complie the project

### ISSUE THREAD

**Issue by markovyao** [t-h-e/HeuristicLab.CFGGP#2]
'HeuristicLab.Problems.CFG.Python.PythonProcess.EvalTask.WaitHandle.get' must declare a body because it is not marked abstract or extern. Automatically implemented properties must define both get and set accessors.	C:\Users\YAO\Desktop\GPGE\HeuristicLab.CFGGP-master\HeuristicLab.Problems.CFG.Python\PythonProcess.cs	265

Metadata file 'C:\Users\YAO\Desktop\GPGE\HeuristicLab\bin\HeuristicLab.Problems.CFG.Python.dll' could not be found	C:\Users\YAO\Desktop\GPGE\HeuristicLab.CFGGP-master\HeuristicLab.Problems.CFG.Python.Views\CSC
 
Can anyone help？  Thanks

**Comment by t-h-e** [comment]
Visual Studio 2013 and 2015 seem to handle properties differently. The code builds with VS2015. For VS2013 or earlier, you have to add a setter to the properties `WaitHandle` and `EvalString` in the private class `EvalTask` within `PythonProcess`

```cs
private class EvalTask {
      public ManualResetEventSlim WaitHandle { get; set; }
      public string EvalString { get; set; }
```

**Comment by markovyao** [comment]
thanks.  now  it works
