### ISSUE TITLE
OperatorExecutionException

### ISSUE THREAD

**Issue by markovyao** [t-h-e/HeuristicLab.CFGGP#3]
Is there any handbook to use the CFGGP?   I got followed errors and failed to fix them.   perhaps some inputs are missing.  

HeuristicLab version: 3.3.14.14190
OperatorExecutionException: An exception was thrown by the operator "CFGTrainingBestSolutionAnalyzer<ICFGProblemData>" [C:\Users\YAO\Desktop\GPGE\HeuristicLab 3.3.14\HeuristicLab.Problems.CFG.dll: 3.3.13.0]: Index was outside the bounds of the array.
   at HeuristicLab.SequentialEngine.SequentialEngine.Run(CancellationToken cancellationToken)
   at HeuristicLab.Core.Engine.Run(Object state)
   at System.Threading.Tasks.Task.Execute()
-----
IndexOutOfRangeException: Index was outside the bounds of the array.
   at HeuristicLab.Problems.CFG.CFGTrainingBestSolutionAnalyzer`1.Apply() in c:\Users\YAO\Desktop\GPGE\HeuristicLab.CFGGP-master\HeuristicLab.Problems.CFG\Analyzer\CFGTrainingBestSolutionAnalyzer.cs:line 140
   at HeuristicLab.Operators.Operator.Execute(IExecutionContext context, CancellationToken cancellationToken)
   at HeuristicLab.SequentialEngine.SequentialEngine.Run(CancellationToken cancellationToken)

**Comment by t-h-e** [comment]
As it is a plugin for HeuristicLab, it is supposed to work in the same/similar way as other plugins. Tutorial videos for HL are available on [youtube](https://www.youtube.com/playlist?list=PL547A94670DA695EE).

At the moment no explicit HowTo guide is available for this plugin, but it is on my ToDo list. Therefore, I hope this short explanation helps you.

HeuristicLab.CFGGP adds two problems to HL. "Context Free Grammar Problem" and "CFG Python Problem". A few benchmark problems are available for the second one, through a dropdown list. Python has to be added to your PATH variable or you can set the path yourself in the PythonProcess parameter.

"Context Free Grammar Problem" requires a grammar in [BNF](https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form) form, which has to be set in the `GrammarBNF` parameter. If it is a valid BNF grammar, a new parameter `Grammar` should appear. To evaluate the individuals, you are required to implement the `Evaluator` parameter in HL, similar to [scripting in HL](https://www.youtube.com/watch?v=bJF2STyaFWU&index=7&list=PL547A94670DA695EE), or write your own plugin which provides an evaluator that implements `ICFGEvaluator<ICFGProblemData>`

**Comment by t-h-e** [comment]
I have attached an example of a `Context Free Grammar Problem` that can be run straight away. The problem contains a grammar and an implemented `CFGProgrammableEvaluator` for a sorting network with 12 inputs.

[CFG - Sorting Network - Example.zip](https://github.com/t-h-e/HeuristicLab.CFGGP/files/639908/CFG.-.Sorting.Network.-.Example.zip)

I maybe should change the default `Context Free Grammar Problem` to something that can be run.
